export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";
export const FETCH_TWEETS_REQUEST = "FETCH_TWEETS_REQUEST";
export const FETCH_TWEETS = "FETCH_TWEETS";
export const FETCH_TWEETS_ERROR = "FETCH_TWEETS_ERROR";
export const ADD_SEARCH_TERM = "ADD_SEARCH_TERM";
